# Generated by Django 4.0.4 on 2022-05-12 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('data_aplicacao', models.DateField()),
                ('idagencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencia.agencia')),
                ('idconta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.conta')),
            ],
        ),
    ]
