# Generated by Django 4.0.4 on 2022-05-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('TP', 'Transferência Pix'), ('TT', 'Transferência TED'), ('TD', 'Transferência DOC'), ('PB', 'Pagamento de Boleto')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('data_execucao', models.DateTimeField(blank=True)),
                ('codigo_boleto', models.CharField(blank=True, max_length=999)),
                ('conta_origem', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='conta_envia', to='conta.conta')),
                ('conta_receber', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conta_recebe', to='conta.conta')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.operacao')),
            ],
            options={
                'unique_together': {('conta_origem', 'conta_receber')},
            },
        ),
    ]
