# Generated by Django 4.0.4 on 2022-05-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterModelOptions(
            name='operacao',
            options={'verbose_name_plural': 'Operações'},
        ),
    ]
