# Generated by Django 4.0.4 on 2022-05-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('vencimento', models.DateField()),
                ('jurus', models.DecimalField(decimal_places=2, default=5.5, max_digits=3)),
                ('status', models.CharField(choices=[('PA', 'Pagamento Aprovado'), ('PN', 'Pagamento Não Identificado')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField(max_length=16, unique=True)),
                ('validade', models.DateField()),
                ('cvv', models.IntegerField(max_length=3)),
                ('bandeira', models.CharField(choices=[('EL', 'ELO'), ('VS', 'Visa'), ('HC', 'HiperCard'), ('MC', 'MasterCard')], max_length=2)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=9)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.conta')),
            ],
        ),
    ]
