# Generated by Django 4.0.4 on 2022-05-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('MC', 'MasterCard'), ('VS', 'Visa'), ('HC', 'HiperCard'), ('EL', 'ELO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('PN', 'Pagamento Não Identificado'), ('PA', 'Pagamento Aprovado')], max_length=2),
        ),
    ]
