# Generated by Django 4.0.4 on 2022-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaocredito',
            options={'verbose_name': 'Cartão de Crédito', 'verbose_name_plural': 'Cartões de Crédito'},
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('EL', 'ELO'), ('MC', 'MasterCard'), ('VS', 'Visa'), ('HC', 'HiperCard')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='numero',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
