# Generated by Django 4.0.4 on 2022-05-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0002_alter_cartaocredito_bandeira_alter_cartaocredito_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('EL', 'ELO'), ('MC', 'MasterCard'), ('HC', 'HiperCard'), ('VS', 'Visa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='numero',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('PA', 'Pagamento Aprovado'), ('PN', 'Pagamento Não Identificado')], max_length=2),
        ),
    ]
