# Generated by Django 4.0.4 on 2022-05-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0005_alter_cartaocredito_bandeira_alter_fatura_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaocredito',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('EL', 'ELO'), ('VS', 'Visa'), ('HC', 'HiperCard'), ('MC', 'MasterCard')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='numero',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('PA', 'Pagamento Aprovado'), ('PN', 'Pagamento Não Identificado')], max_length=2),
        ),
    ]
