# Generated by Django 4.0.4 on 2022-05-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0007_alter_cartaocredito_bandeira_alter_fatura_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaocredito',
            options={'verbose_name': 'Cartão de Crédito', 'verbose_name_plural': 'Cartões de Crédito'},
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('EL', 'ELO'), ('MC', 'MasterCard'), ('HC', 'HiperCard'), ('VS', 'Visa')], max_length=2),
        ),
    ]
