# Generated by Django 4.0.4 on 2022-05-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0007_alter_cartaocredito_bandeira_alter_fatura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('MC', 'MasterCard'), ('HC', 'HiperCard'), ('VS', 'Visa'), ('EL', 'ELO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('PA', 'Pagamento Aprovado'), ('PN', 'Pagamento Não Identificado')], max_length=2),
        ),
    ]
