# Generated by Django 4.0.4 on 2022-06-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0008_alter_cartaocredito_bandeira_alter_fatura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('MC', 'MasterCard'), ('EL', 'ELO'), ('VS', 'Visa'), ('HC', 'HiperCard')], max_length=2),
        ),
    ]
