# Generated by Django 4.0.4 on 2022-06-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0009_alter_cartaocredito_bandeira_alter_fatura_status'),
        ('cartao', '0010_alter_cartaocredito_bandeira_alter_fatura_status'),
    ]

    operations = [
    ]
