# Generated by Django 4.0.4 on 2022-06-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0011_merge_20220602_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('EL', 'ELO'), ('VS', 'Visa'), ('HC', 'HiperCard'), ('MC', 'MasterCard')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='validade',
            field=models.CharField(max_length=11),
        ),
    ]
