# Generated by Django 4.0.4 on 2022-06-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0012_alter_cartaocredito_bandeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('HC', 'HiperCard'), ('VS', 'Visa'), ('MC', 'MasterCard'), ('EL', 'ELO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('PA', 'Pagamento Aprovado'), ('PN', 'Pagamento Não Identificado')], max_length=2),
        ),
    ]
