# Generated by Django 4.0.4 on 2022-05-12 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimento', '0001_initial'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='idfuncionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionario.funcionario'),
        ),
    ]
