# Generated by Django 4.0.4 on 2022-05-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='servico',
            field=models.CharField(choices=[('AS', 'Ajuda com Suporte'), ('AP', 'Ajuda com Pagamentos'), ('A', 'Ajuda com Senha'), ('AC', 'Ajuda com Cartão'), ('AR', 'Ajuda com Reembolsos')], max_length=2),
        ),
    ]
