# Generated by Django 4.0.4 on 2022-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_alter_atendimento_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='assunto',
            field=models.CharField(default='', max_length=150),
        ),
    ]
