# Generated by Django 4.0.4 on 2022-05-30 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_remove_funcionario_tipo'),
        ('atendimento', '0003_atendimento_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='idfuncionario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='funcionario.funcionario'),
        ),
    ]
