# Generated by Django 4.0.4 on 2022-05-30 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_remove_funcionario_tipo'),
        ('atendimento', '0004_alter_atendimento_data_alter_atendimento_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='idfuncionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionario.funcionario'),
        ),
    ]
