# Generated by Django 4.0.4 on 2022-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='id',
        ),
        migrations.AlterField(
            model_name='conta',
            name='numero',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('CS', 'Conta Salario')], default='CC', max_length=2),
        ),
    ]
