# Generated by Django 4.0.4 on 2022-05-12 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('salario', models.CharField(max_length=255)),
                ('comissao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=2)),
                ('idagencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencia.agencia')),
            ],
        ),
    ]
