# Generated by Django 4.0.4 on 2022-05-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa_fisica',
            options={'verbose_name': 'Pessoa Física', 'verbose_name_plural': 'Pessoas Físicas'},
        ),
        migrations.AddField(
            model_name='pessoa_fisica',
            name='RG',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
