# Generated by Django 4.0.4 on 2022-05-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_pessoa_fisica_options_pessoa_fisica_rg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
