# Generated by Django 4.0.4 on 2022-06-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa_fisica',
            name='nascimento',
        ),
    ]
