# Generated by Django 4.0.4 on 2022-05-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencia',
            options={'verbose_name': 'Agência', 'verbose_name_plural': 'Agências'},
        ),
    ]
